#baseURL = 'https://chopprr.cc/'
languageCode = 'en-us'
title = 'Linux Server Maintenance'
theme = ['lugo', 'matomo']

# Theme used
[module]
  [[module.imports]]
    path = 'github.com/LukeSmithxyz/lugo'

[markup]
  defaultMarkdownHandler = 'goldmark' # Set goldmark as markup renderer

  # Required to display html tags used in markdown files (<u>, <br>, etc..)
  [markup.goldmark.renderer]
    unsafe = true

sectionPagesMenu = 'main'

# Theme configuration
[params]
  github = "https://github.com/exposedlan/linux-server-maintenace-guide"
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Article tags:"
  favicon = "/favicon.ico"

  #list items
  datesinlist = false
  authorsinlist = false

  #footer items
  nextprev = true
  taglist = true
  showrss = true

# Matomo (analytics) configuration
[params.matomo]
  url = "https://analytics.chopprr.cc/"
  disableSRI = true
  id = 1
